name: .NET

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      id: Build
      run: dotnet publish RPAK2L --nologo --no-restore -c Release -f net5.0 -r linux-x64 -o ./Artifact/
    - name: Delete deps.json
      run: rm -f ./Artifact/RPAK2L.deps.json
    - name: Set Tool Executable Flag
      run: chmod +x ./Artifact/RPAK2L
    - name: Set Updater Executable Flag
      run: chmod +x ./Artifact/updater
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Linux_x64_Release
        path: ./Artifact/
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      id: Build
      run: dotnet publish RPAK2L --nologo --no-restore -c Release -r win-x64 -o ./Artifact/
    - name: Delete deps.json
      run: del Artifact\RPAK2L.deps.json
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Windows_x64_Release
        path: ./Artifact
