name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      id: Build
      run: dotnet build RPAK2L --no-restore -c Linux
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: ${{ steps.Build.outputs.artifactpath }}
  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      id: Build
      run: dotnet build RPAK2L --no-restore -c Windows
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: ${{ steps.Build.outputs.artifactpath }}
